package io.appwrite.models

/**
 * This file is auto-generated by the Appwrite CLI. 
 * You can regenerate it by running `appwrite types -l kotlin E:\Proyectos\Frondend\Multiplataforma (Flutter)\Apiario\Pregonero`.
 */

enum class Category {
    fiction,
    nonfiction
}

data class Books(
    val name: String,
    val author: String,
    val release_year: String?,
    val category: Category?,
    val genre: List<String>?,
    val is_checked_out: Boolean
)