package io.appwrite.models

import com.elitec.compralibre.domain.entities.typeOf.Roles

/**
 * This file is auto-generated by the Appwrite CLI. 
 * You can regenerate it by running `appwrite types -l kotlin E:\Proyectos\Frondend\Android\Nuevos\Mercado`.
 */

data class UserAuth(
    val id: String,
    val name: String,
    val email: String?,
    val phone: String?,
    val photoUrl: String?,
    val createAt: String = System.currentTimeMillis().toIso8601(),
    val role: String? = Roles.GUEST.name
) {
    companion object {
        fun fromDocument(document: Document<Map<String, Any>>): UserAuth {
            return UserAuth(
                id = document.data["id"] as String,
                email = document.data["email"] as? String,
                name = document.data["name"] as String,
                photoUrl = document.data["photoUrl"] as? String,
                role = document.data["role"] as? String ?: "CUSTOM_USER",
                phone = document.data["phone"] as? String,
                createAt = document.data["createAt"] as String
            )
        }
    }

    fun toDocumentData(): Map<String, Any?> {
        return mapOf(
            "id" to id,
            "email" to email,
            "name" to name,
            "photoUrl" to photoUrl,
            "role" to role,
            "createAt" to createAt,
            "phone" to phone
        )
    }
}